### ISSUE TITLE
Custom naming of files managed by the CrxArchive class

### ISSUE THREAD

**Issue by Yang-Nankai** [extensionsec/xcavate#14]
https://github.com/extensionsec/xcavate/blob/12269af4e641acc5ad80c54df85b30a89d40f2f6/xcavate/storage/crx_archive.py#L110C1-L113C39

Here exists little problem that when the extension name not the digest, it will rename the extension name to the digest.

```python
@property
    def crx_name(self) -> str:
        return f"{self.digest}.crx"
```

When I place `test_sample_extension.crx`, when running the tests code, the file will be changed to `2fbb9899b0228ed33a5dd195a9feaa38.crx`, making it unreadable.

And now my solution is just that changed the real logic to `pass`.

```python
    def update_name(self):
        current_name = os.path.basename(self.crx_path)
        if current_name != self.crx_name:
            # here just for test pass
            # self.rename(self.crx_name)
            pass
```

**Comment by Yang-Nankai** [comment]
Another problem is when the extension manifest file not has the `web_accessible_resources` field. It can't pass the tests, but actually there exists these extensions.

https://github.com/extensionsec/xcavate/blob/12269af4e641acc5ad80c54df85b30a89d40f2f6/tests/storage/test_crx_archive.py#L89C5-L89C49

![image](https://github.com/extensionsec/xcavate/assets/100209158/ce394507-4ae0-4e4d-b3d0-851649a1d7e2)

Actually I don't know if every extension has the `web_accessible_resources` field, if so, I think my question is redundant. 😃 

@valbucci

**Comment by Yang-Nankai** [comment]
The same problem also happens here:

https://github.com/extensionsec/xcavate/blob/12269af4e641acc5ad80c54df85b30a89d40f2f6/tests/storage/test_crx_archive.py#L60C1-L67C42

![image](https://github.com/extensionsec/xcavate/assets/100209158/bd15cd04-b228-46f1-9e47-098393d20284)

When the `web_accessible_resources` filed not exists, the `resources` is None, so the `assertEqual(type(resources), list)` will not be passed.

**Comment by valbucci** [comment]
> When I place test_sample_extension.crx, when running the tests code, the file will be changed to 2fbb9899b0228ed33a5dd195a9feaa38.crx, making it unreadable.

When you instantiate a CrxArchive object it will keep track of the extension name. While we could add functionality for custom naming of the CRX files, I believe you should use this functionality for test purposes.

Please refer to the `setUp` and `tearDown` methods of the test suite `test_crx_archive.py`. Note that these methods are called before and after each test method run, respectively. For the code snippet below I used my own branch because it seems that you removed the for-loop that cleaned up the tested CRX files (line 30).

https://github.com/extensionsec/xcavate/blob/70b5da2bf3cb4ada9cf7896555e5bc962341140b/tests/storage/test_crx_archive.py#L24-L37

The way you should handle test samples (especially if you are conducting operations on them) is by making a copy of the original file and operate on it. We do this because if you corrupt accidentally the test sample the original version is retained.

Please, revert to the previous version of these methods, un-comment the renaming logic of `CrxArchive::update_name`, and include your CRX sample in the `setUp` and `tearDown` methods. We can close this issue when you are done; please let me know if you need any further help with this.

**Comment by valbucci** [comment]
I implemented the following function decorator for facilitating the cleanup of test files.
https://github.com/extensionsec/xcavate/blob/09579998d7f243f175af5520e8e1067bd25bed66/tests/common/utils.py#L25-L38

Here is an example of how it can be used, when you need just one test (or few) to perform this cleanup, and not a complete test suite - as `tearDown` would not be an ideal implementation.
https://github.com/extensionsec/xcavate/blob/09579998d7f243f175af5520e8e1067bd25bed66/tests/common/utils.py#L25-L38

**I will now open a new issue for implementing this decorator in the other test methods.**

---

Finally, I updated the property `CrxArchive::crx_name` as follows, allowing to optionally provide a custom namiing to CRX files. 
https://github.com/extensionsec/xcavate/blob/58d941a5bb20c165b48e890634b98aace6a98fae/xcavate/storage/crx_archive.py#L63-L67

Here is an example of how it can be used:
https://github.com/extensionsec/xcavate/blob/58d941a5bb20c165b48e890634b98aace6a98fae/tests/storage/test_crx_archive.py#L42-L43
